repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.13.6
  hooks:
  - id: jshint
- repo: local
  hooks:
  - id: npm test
    name: npm test
    entry: npm test
    language: system
    pass_filenames: false
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
